#!/bin/bash
#this script only installs wdfs and some other dependencies - a webdav filesystem

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
apt-get install checkinstall libfuse-dev libneon27 libneon27-dev python-fuse fuse-utils -y
wget http://noedler.de/projekte/wdfs/wdfs-1.4.2.tar.gz
tar xzvf wdfs-1.4.2.tar.gz
cd wdfs-1.4.2
./configure && make
make install
cd ..
rm wdfs-1.4.2.tar.gz
rm -rf wdfs-1.4.2