#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
apt-get install checkinstall libfuse-dev libneon27 libneon27-dev python-fuse fuse-utils -y
cd src/wdfs-1.4.2
./configure && make
make install
